---
title: "3340 Project"
author: "Jacob, Chris, Cali"
due date: "December 11th 2020"
output: html_document
---
```{r setup, include=FALSE}
setwd("C:\\Users\\jacob\\Desktop") #Please set working directory to where you have the CDC file
library(dplyr)
library(tidyverse)
read.csv("C:\\Users\\jacob\\Desktop\\original_data.csv") -> original_data #Please set file location to where you have the CDC file
```

Removing useless data entries ("Data not available...")
```{r}
filter(original_data, Data_Value_Footnote != "Data not available because sample size is insufficient.") -> df_1

filter(df_1, Data_Value_Footnote != "Data not available because sample size is insufficient.  If data only missing for the confidence interval, the confidence interval was not calculated.") -> df_2
```


Removing irrelevant data columns
```{r}
subset(df_2, select = -c(
  YearEnd, LocationAbbr, Datasource, Class, Data_Value_Unit, Data_Value_Type, Data_Value_Alt, Data_Value_Footnote,   DataValueTypeID, StratificationCategoryId1, StratificationID1, ClassID, TopicID, QuestionID)) -> df_3
```


Removing US Territories (not needed for our analysis)
```{r}
filter(df_3, LocationID < 59) -> df_4
```


INSERTING NEW MADE-UP ROW
```{r}
add_case(df_4, 
YearStart = 2012, LocationDesc = "Alabama", Topic = "Obesity / Weight Status", Question = "Percent of adults aged 18 years and older who have obesity", Data_Value = 29.999, Data_Value_Footnote_Symbol = "", Low_Confidence_Limit = 23.999, High_Confidence_Limit = 33.499, Sample_Size = 1255, Total = "", Age.years. = "", Education = "", Gender = "", Income = "", Race.Ethnicity = "Asian", GeoLocation = "(32.84057112200048, -86.63186076199969)", LocationID = 1, StratificationCategory1 = "Race/Ethnicity", Stratification1 = "Asian"         
         ) -> df_5
filter(df_5, Income != "Data not reported") -> df_6

df_6["311", "Sample_Size"] <- 1974 #This adds our new asian demographic into income (where 1255 was preiovusly unavailable)

```


Marking each state by its region 
```{r}
newCol <- c(1:44702) #Creating a new column that will turn into region ID
df_7 <- cbind(df_6, RegionID = newCol) #The numbering 1-44702 also helps check for missed rows

for (i in seq_along(df_7$LocationID)) {    #REGION 4, SOUTH
  if(df_7$LocationID[i] == 1 | df_7$LocationID[i] == 48 | df_7$LocationID[i] == 40 | df_7$LocationID[i] == 5 | df_7$LocationID[i] == 22 | df_7$LocationID[i] == 28 | df_7$LocationID[i] == 47 | df_7$LocationID[i] == 21 | df_7$LocationID[i] == 13 | df_7$LocationID[i] == 12 | df_7$LocationID[i] == 37 | df_7$LocationID[i] == 45 | df_7$LocationID[i] == 51 | df_7$LocationID[i] == 54 | df_7$LocationID[i] == 24 | df_7$LocationID[i] == 10 | df_7$LocationID[i] == 11) {
    df_7$RegionID[i] <- 4
   }
}

for (i in seq_along(df_7$LocationID)) {    #REGION 3, NORTHEAST
  if(df_7$LocationID[i] == 23 | df_7$LocationID[i] == 33 | df_7$LocationID[i] == 50 | df_7$LocationID[i] == 25 | df_7$LocationID[i] == 9 | df_7$LocationID[i] == 44 | df_7$LocationID[i] == 36 | df_7$LocationID[i] == 34 | df_7$LocationID[i] == 42) {
    df_7$RegionID[i] <- 3
   }
}

for (i in seq_along(df_7$LocationID)) {    #REGION 2, MIDWEST
  if(df_7$LocationID[i] == 38 | df_7$LocationID[i] == 46 | df_7$LocationID[i] == 31 | df_7$LocationID[i] == 20 | df_7$LocationID[i] == 27 | df_7$LocationID[i] == 19 | df_7$LocationID[i] == 29 | df_7$LocationID[i] == 55 | df_7$LocationID[i] == 17 | df_7$LocationID[i] == 26 | df_7$LocationID[i] == 18 | df_7$LocationID[i] == 39) {
    df_7$RegionID[i] <- 2
   }
}

for (i in seq_along(df_7$LocationID)) {    #REGION 1, WEST
  if(df_7$LocationID[i] == 53 | df_7$LocationID[i] == 41 | df_7$LocationID[i] == 6 | df_7$LocationID[i] == 30 | df_7$LocationID[i] == 16 | df_7$LocationID[i] == 56 | df_7$LocationID[i] == 32 | df_7$LocationID[i] == 49 | df_7$LocationID[i] == 8 | df_7$LocationID[i] == 4 | df_7$LocationID[i] == 35) {
    df_7$RegionID[i] <- 1
   }
}

filter(df_7, LocationDesc != "Alaska") -> df_8
filter(df_8, LocationDesc != "Hawaii") -> df_9
```


#Giving each income range a value instead of using "$25,000 - $34,999" every time
```{r}
newCol <- c(1:42924) 
df_10 <- cbind(df_9, IncomeID = newCol) 

for (i in seq_along(df_10$Income)) {
  if(df_10$Income[i] == "Less than $15,000") {
    df_10$IncomeID[i] <- 1
  } else if (df_10$Income[i] == "$15,000 - $24,999") {
    df_10$IncomeID[i] <- 2
  } else if (df_10$Income[i] == "$25,000 - $34,999") {
    df_10$IncomeID[i] <- 3
  } else if (df_10$Income[i] == "$35,000 - $49,999") {
    df_10$IncomeID[i] <- 4
  } else if (df_10$Income[i] == "$50,000 - $74,999") {
    df_10$IncomeID[i] <- 5
  } else if (df_10$Income[i] == "$75,000 or greater") {
    df_10$IncomeID[i] <- 6
  } else {
    df_10$IncomeID[i] <- ""
  }
}
df_total <- df_10
```

```{r}
filter(df_total, Question == "Percent of adults aged 18 years and older who have obesity") -> df_question
filter(df_question, IncomeID != "") -> df_prime

subset(df_prime, select = -c(
  Data_Value_Footnote_Symbol, Total, Age.years., Education, Gender, Race.Ethnicity, LocationID, Stratification1, StratificationCategory1
)) -> df_prime
```

```{r}
write.csv(df_prime, file = "edited_data_prime.csv")
```