---
title: "3340_Project_Analysis"
author: "Jacob, Chris, Cali"
date: "09/12/2020"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(tidyverse)
library(car)
library(MASS)
library(matlib)
read.csv("C:\\Users\\jacob\\Desktop\\data_prime.csv") -> df
```


```{r, message=FALSE}
mean(df$obesity) -> mObesity
mean(df$fruit) -> mFruit
mean(df$veg) -> mVeg

newCol <- c(1:918) 
df <- cbind(df, y = newCol)
for (i in seq_along(df$y)) {
  df$y[i] = df$obesity[i] - mObesity
}

newCol <- c(1:918) 
df <- cbind(df, x1 = newCol)
for (i in seq_along(df$x1)) {
  df$x1[i] = df$fruit[i] - mFruit
}

newCol <- c(1:918) 
df <- cbind(df, x2 = newCol)
for (i in seq_along(df$x2)) {
  df$x2[i] = df$veg[i] - mVeg
}
```

```{r}
lm(y ~ x1, data = df) -> lm1
summary(lm1)
lm(y ~ x2, data = df) -> lm2
summary(lm2)
lm(y ~ x1 + x2, data = df) -> lm1.2
summary(lm1.2)
#lm(y ~ x1*x2, data = df) -> lm12
#summary(lm12)
```

```{r, message=FALSE}
attach(df)
plot(x1,y, xlab = "Less than one fruit per day (Normalized, μ = 40.35%)", ylab = "Rate of obesity (Normalized, μ = 30.08%)")
abline(lm(y ~ x2))
mylabel = bquote(italic(R)^2 == .(format(0.4112)))
text(x = 17, y = -12.5, labels = mylabel)
```

```{r, message=FALSE}
plot(x2,y, xlab = "Less than one vegetable per day (Normalized, μ = 24.18%)", ylab = "Rate of obesity (Normalized, μ = 30.08%)")
abline(lm(y ~ x2))
mylabel = bquote(italic(R)^2 == .(format(0.3616)))
text(x = 29.5, y = -12.5, labels = mylabel)
```

```{r}
obeEst<-data.frame(x1=59.65,x2=75.82)
predict.lm(lm1.2,newdata=obeEst,interval="prediction")

obeEst<-data.frame(x1=-40.35,x2=-24.18)
predict.lm(lm1.2,newdata=obeEst,interval="prediction")
```

```{r}
dfedit <- df[-c(197,269,700),]
dfedit2 <- df[-c(162,202,205),]
dfedit3 <- df[-c(197,269,700,162,202,205)]
summary(lm(y ~ x1 + x2, data = dfedit))
summary(lm(y ~ x1 + x2, data = dfedit2))
summary(lm(y ~ x1 + x2, data = dfedit3))
```

```{r}
rlm(y ~ x1, data = df) -> rlm1
rlm(y ~ x2, data = df) -> rlm2
rlm(y ~ x1 + x2, data = df) -> rlm1.2


lm1$coefficients
rlm1$coefficients

lm2$coefficients
rlm2$coefficients

lm1.2$coefficients
rlm1.2$coefficients
```

```{r}
subset(df, select = c(y,x1,x2)) -> df_s
df_m <- as.matrix(df_s)
subset(df_s, select = c(y)) -> yvec
as.matrix((yvec)) -> ymat
subset(df_s, select = c(x1, x2)) -> xvec
cbind(v = 1,xvec) -> xvec
as.matrix(xvec) -> xmat

t(xmat) -> txmat
txmat %*% xmat -> ttxmat
inv(ttxmat) -> invttxmat

txmat %*% ymat -> txymat

invttxmat %*% txymat -> beta
```

```{r fig.height=5,fig.width=8}
plot(lm1.2)
residualPlots(lm1.2, type = "rstudent")
vif(lm1.2)
```
