---
title: "3340 Project"
author: "Jacob, Chris, Cali"
due date: "December 11th 2020"
output: html_document
---
```{r setup, include=FALSE}
setwd("C:\\Users\\jacob\\Desktop") #Please set working directory to where you have the CDC file
library(dplyr)
library(tidyverse)
read.csv("C:\\Users\\jacob\\Desktop\\original_data.csv") -> original_data #Please set file location to where you have the CDC file
```

Removing useless data entries ("Data not available...")
```{r}
filter(original_data, Data_Value_Footnote != "Data not available because sample size is insufficient.") -> df_1

filter(df_1, Data_Value_Footnote != "Data not available because sample size is insufficient.  If data only missing for the confidence interval, the confidence interval was not calculated.") -> df_2
```


Removing irrelevant data columns
```{r}
subset(df_2, select = -c(
  YearEnd, LocationAbbr, Datasource, Class, Data_Value_Unit, Data_Value_Type, Data_Value_Alt, Data_Value_Footnote,   DataValueTypeID, StratificationCategoryId1, StratificationID1, ClassID, TopicID, QuestionID)) -> df_3
```


Removing US Territories (not needed for our analysis)
```{r}
filter(df_3, LocationID < 59) -> df_4
```


INSERTING NEW MADE-UP ROW
```{r}
add_case(df_4, 
YearStart = 2012, LocationDesc = "Alabama", Topic = "Obesity / Weight Status", Question = "Percent of adults aged 18 years and older who have obesity", Data_Value = 29.999, Data_Value_Footnote_Symbol = "", Low_Confidence_Limit = 23.999, High_Confidence_Limit = 33.499, Sample_Size = 1255, Total = "", Age.years. = "", Education = "", Gender = "", Income = "", Race.Ethnicity = "Asian", GeoLocation = "(32.84057112200048, -86.63186076199969)", LocationID = 1, StratificationCategory1 = "Race/Ethnicity", Stratification1 = "Asian"         
         ) -> df_5
filter(df_5, Income != "Data not reported") -> df

df["311", "Sample_Size"] <- 1974

```

```{r}
write.csv(df, file = "edited_data2.csv")
```